consumerGroupPrefix: kafka_fhir_submission_local_
healthReportingIntervalMs: 5000
allowedConsumerDelayMs: 60000

consumerDefaults:
  fetchMinBytes: 65536
  fetchMaxWaitMs: 1000
  maxMessagesBeforeCommit: 200
  maxTimeBeforeCommitMs: 1000
  autoOffsetReset: earliest
  maxPartitionFetchBytes: 10485760
  socketReceiveBufferBytes: 524288
  maxPollRecords: 10000

kafkaBrokers:
kafkaBrokers:
  - id: localsingle
    hostS: "kafka:9092"
  - id: local
    hosts: "localhost:9092,localhost:9093,localhost:9094"
  - id: sandbox
    hosts: "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094"
  - id: docker
    hosts: "192.168.99.100:9092"

connectors:
  - id: dev_andrew_submission
    sourceBroker: localsingle
    sourceTopic: fhir-submission
    targetCluster: "sandbox/analytics"
    targetTable: "%SOURCE%"
    threads: 1