version: '3'
services:
  gui:
    image: web-hml-fhir:latest
    ports:
      - "9005:9005"
  serviceconversion:
    image: service-hml-fhir:latest
    ports:
      - "8099:8099"
    links:
      - mongodb
      - kafka
  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
  kafka:
    image: spotify/kafka:latest
    ports:
      - "2181:2181"
      - "9092:9092"
